/**
 * User API
 * API for creating and retrieving users
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package com.polo.api.model

import com.polo.api.model.JsonPatchInnerOneOf
import com.polo.api.model.JsonPatchInnerOneOf1
import com.polo.api.model.JsonPatchInnerOneOf2
import com.polo.api.model.Path
import jakarta.validation.constraints.*
import jakarta.validation.Valid
typealias JsonPatchInner = Any

