/**
 * User API
 * API for creating and retrieving users
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package com.polo.api.model

import com.polo.api.model.Path
import jakarta.validation.constraints.*
import jakarta.validation.Valid
import com.fasterxml.jackson.annotation.JsonProperty
/**
 * 
 *
 * @param path 
 * @param op The operation to perform.
 */


data class JsonPatchInnerOneOf1 (


    @JsonProperty("path")
    @field:Valid
    @field:NotNull
    val path: Path,

    /* The operation to perform. */

    @JsonProperty("op")
    @field:Valid
    @field:NotNull
    val op: JsonPatchInnerOneOf1.Op

) {

    /**
     * The operation to perform.
     *
     * Values: remove
     */
    enum class Op(val value: kotlin.String) {
        @JsonProperty(value = "remove") remove("remove");
    }
}

