/**
 * User API
 * API for creating and retrieving users
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package com.polo.api.model

import com.polo.api.model.Path
import jakarta.validation.constraints.*
import jakarta.validation.Valid
import com.fasterxml.jackson.annotation.JsonProperty
/**
 * 
 *
 * @param path 
 * @param op The operation to perform.
 * @param `value` The value to add, replace or test.
 */


data class JsonPatchInnerOneOf (


    @JsonProperty("path")
    @field:Valid
    @field:NotNull
    val path: Path,

    /* The operation to perform. */

    @JsonProperty("op")
    @field:Valid
    @field:NotNull
    val op: JsonPatchInnerOneOf.Op,

    /* The value to add, replace or test. */

    @JsonProperty("value")
    @field:Valid
    @field:NotNull
    val `value`: kotlin.Any

) {

    /**
     * The operation to perform.
     *
     * Values: add,replace,test
     */
    enum class Op(val value: kotlin.String) {
        @JsonProperty(value = "add") add("add"),
        @JsonProperty(value = "replace") replace("replace"),
        @JsonProperty(value = "test") test("test");
    }
}

