/**
 * User API
 * API for creating and retrieving users
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package com.polo.api.model

import jakarta.validation.constraints.*
import jakarta.validation.Valid
import com.fasterxml.jackson.annotation.JsonProperty
/**
 * 
 *
 * @param id 
 * @param name 
 * @param phone 
 */


data class User (


    @JsonProperty("id")
    @field:Valid
    @field:NotNull
    val id: kotlin.String,


    @JsonProperty("name")
    @field:Valid
    @field:NotNull
    val name: kotlin.String,


    @JsonProperty("phone")
    @field:Valid
    @field:NotNull
    val phone: kotlin.String

)

